apiVersion: v1
kind: Service
metadata:
  name: my-feed-service
  labels:
    run: my-feed-service
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    service: reverseproxy
    type: LoadBalancer
